blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Discord Chat
    url: https://discord.com/invite/vue
    about: Ask questions and discuss with other Vue Language Tools users in real time.
  - name: â“ Questions & Discussions
    url: https://github.com/vuejs/language-tools/discussions
    about: Use GitHub discussions for message-board style questions and discussions.
