name: Publish to Open VSX and VSCode Marketplace

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  publish-ovsx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm

      - name: Install global tools
        run: pnpm install -g ovsx

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        working-directory: extensions/vscode
        run: npm run build

      - name: Publish to Open VSX
        working-directory: extensions/vscode
        env:
          OVSX_PAT: ${{ secrets.OVSX_PAT }}
        run: ovsx publish

      - name: Publish to VSCode Marketplace
        working-directory: extensions/vscode
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
        run: vsce publish
